### PR TITLE
Fix AWS timestamp formats

### LINKED ISSUE #387: Kinesis: invalid signature
The following code:

```scala
import cats.effect.IOApp

import cats.effect.IO
import org.http4s.ember.client.EmberClientBuilder
import smithy4s.aws.AwsClient
import smithy4s.aws.http4s._
import org.http4s.implicits._
import com.amazonaws.kinesis._
import smithy4s.aws.AwsEnvironment
import smithy4s.aws.kernel.AwsRegion

object Main extends IOApp.Simple {

  def run: IO[Unit] = EmberClientBuilder
    .default[IO]
    .build
    .flatMap { c =>
      Kinesis.awsClient(c, AwsRegion.US_EAST_1)
    }
    .use { k =>
      k.listStreams().run
    }
    .flatMap(IO.println(_))

}
```

fails with the following exception:

```
[E] smithy4s.aws.AwsClientError: {"__type":"InvalidSignatureException","message":"Date in Credential scope does not match YYYYMMDD from ISO-8601 version of date from HTTP. "}
[E]     at smithy4s.aws.internals.AwsUnaryEndpoint.$anonfun$run$3(AwsUnaryEndpoint.scala:83)
[E]     at map @ smithy4s.aws.AwsErrorTypeDecoder$.$anonfun$fromResponse$1(AwsErrorTypeDecoder.scala:50)
[E]     at flatMap @ smithy4s.aws.internals.AwsUnaryEndpoint.$anonfun$run$2(AwsUnaryEndpoint.scala:72)
[E]     at >>$extension @ org.typelevel.keypool.KeyPool$Builder.keepRunning$1(KeyPool.scala:337)
[E]     at run$ @ Main$.run(Main.scala:12)
[E]     at >>$extension @ org.typelevel.keypool.KeyPool$Builder.keepRunning$1(KeyPool.scala:337)
[E]     at run$ @ Main$.run(Main.scala:12)
[E]     at >>$extension @ org.typelevel.keypool.KeyPool$Builder.keepRunning$1(KeyPool.scala:337)
[E]     at run$ @ Main$.run(Main.scala:12)
[E]     at delay @ fs2.io.net.SocketGroupCompanionPlatform$AsyncSocketGroup.$anonfun$client$3(SocketGroupPlatform.scala:56)
[E]     at >>$extension @ org.typelevel.keypool.KeyPool$Builder.keepRunning$1(KeyPool.scala:337)
[E]     at run$ @ Main$.run(Main.scala:12)
[E]     at delay @ fs2.io.net.SocketCompanionPlatform.$anonfun$forAsync$2(SocketPlatform.scala:43)
```

[Reproduction project](https://github.com/kubukoz/demos/tree/smithy4s-kinesis-creds)

### PR DESCRIPTION
**Pull request by kubukoz**
An ugly implementation that I intend to clean up if this works.

Thanks @andyjayne for the tests!

Closes #387.

### CODE REVIEW

**Comment by kubukoz** [comment]
Seems to work locally in a `ListStreams`/`ListShards` scenario!

**Review by Baccata — APPROVED** [review]

**Comment by Baccata** [comment]
🎉

**Comment by plokhotnyuk** [comment]
Sorry, it was my fault... Thanks for the fix and missing tests!

**Comment by Baccata** [comment]
No worries, thanks for having a look !

**Comment by kubukoz** [comment]
Tests are courtesy of @andyjayne :)

**Pull request merged**
