### PR TITLE
add logo to microsite

### PR DESCRIPTION
**Pull request by lewisjkl**
Updates favicon and site logo. Adds image to hero section on main page. Attached are mobile and full preview images.

CleanShot 2022-10-19 at 12 06 17
CleanShot 2022-10-19 at 12 06 05

### CODE REVIEW

**Comment by daddykotex** [comment]
Love the PR, thanks for the screenshots.

**Review by daddykotex — APPROVED** [review]

**Comment by kubukoz** [comment]
image

I think this could use some more contrast, but it does look better in high resolution

**Review by kubukoz — APPROVED** [review]

**Comment by Baccata** [comment]
Apologies, but it's GRAPHIC DESIGN NITPICK TIME. 

* I hadn't realised the contrast problem that the "Scala" red was gonna create with the light blue that has been our logo. We could just go from red to black (or much darker red) to try and fix ? 
* As @kubukoz mentioned, the border of the hammer also has a contrast problem with the background. 
* The layout is off : the hammer forcing the subtext to the right makes it somewhat ugly. Additionally, I think the hammer is too large wrt the title and could do with re-sizing.

**Comment by lewisjkl** [comment]
Addressed feedback in my last commit https://github.com/disneystreaming/smithy4s/pull/532/commits/a5768beba03a4d761a3b8dd696322dc508a81e1e
CleanShot 2022-10-20 at 09 52 12
CleanShot 2022-10-20 at 09 52 20

**Review by Baccata — APPROVED** [review]

**Comment by kubukoz** [comment]
I'm not seeing this on the website, is there anything we need to do to enable this? Make a release?

**Comment by daddykotex** [comment]
yeah the microsite is only updated on publish, we could tweak that.

**Comment by lewisjkl** [comment]
Added a PR that would do this in #536. Lmk what you think.

**Comment by daddykotex** [comment]
related: https://github.com/disneystreaming/smithy4s/pull/540

**Pull request merged**
