### PR TITLE
Make generated case classes final

### LINKED ISSUE #913: Make generated case classes `final`
As per the title.

### PR DESCRIPTION
**Pull request by jgoday**
Fixes #913.

Generate final case classes for unions and products.

### CODE REVIEW

**Comment by jgoday** [comment]
Should autogenerated examples be commited to (modules/example) ?

**Comment by kubukoz** [comment]
> Should autogenerated examples be commited to (modules/example) ?

Yes - they serve as a sort of "snapshot test". I believe CI will fail if you have uncommitted changes after running the tests (which would trigger the code generation).

**Comment by kubukoz** [comment]
I think you'll have to run `scalafmtAll` and commit the differences for the PR to pass CI

**Comment by jgoday** [comment]
> I think you'll have to run `scalafmtAll` and commit the differences for the PR to pass CI

Sorry for that, I have completely forgotten :(

**Review by Baccata — APPROVED** [review]
Good work, thanks for this !

**Pull request merged**
