### PR TITLE
Make decline cli's `service` parameter implicit

### PR DESCRIPTION
**Pull request by kubukoz**

### CODE REVIEW

**Comment by kubukoz** [comment]
This _is_ clearly breaking, right?

```
// old
public smithy4s.decline.Smithy4sCli(com.monovore.decline.Opts<smithy4s.decline.Entrypoint<Alg, F>>, smithy4s.Service<Alg>, cats.MonadError<F, java.lang.Throwable>);
public smithy4s.decline.Smithy4sCli(com.monovore.decline.Opts<smithy4s.decline.Entrypoint<Alg, F>>, cats.MonadError<F, java.lang.Throwable>, smithy4s.Service<Alg>);
// new
```

Apparently MiMa is off in the decline module:

```
[info] [decline] decline: mimaPreviousArtifacts is empty, not analyzing binary compatibility.
```

**Comment by Baccata** [comment]
It is breaking but you could make a smart constructor in the companion object instead of breaking ?

**Comment by Baccata** [comment]
> Apparently MiMa is off in the decline module:

let's turn it on

**Comment by kubukoz** [comment]
> It is breaking but you could make a smart constructor in the companion object instead of breaking ?

won't help my usecase as I'm mostly doing `extends Smithy4sCli`... but I can stop doing that, too. Or wait for 0.18.

**Comment by Baccata** [comment]
> won't help my usecase as I'm mostly doing extends Smithy4sCli... but I can stop doing that, too. Or wait for 0.18. 

mmm you add an additional constructor ?

**Comment by kubukoz** [comment]
or that yeah

**Review by Baccata — APPROVED** [review]

**Pull request merged**
