### PR TITLE
Merge main back into 0.16.0 before official release.

### PR DESCRIPTION
**Pull request by daddykotex**
I botched the 0.16.0 release by merging an incomplete branch (from my local git repo). 

This is a PR to resolve conflict in the 0.16.0 branch. I will use https://github.com/disneystreaming/smithy4s/pull/457 to do the merge & release this time.

This is my mistake, sorry for the noise.

### CODE REVIEW

**Review by lewisjkl — APPROVED** [review]

**Comment by lewisjkl** [comment]
Ah yeah mima is mad. We could update the base mima version to 0.16.1?

**Comment by Baccata** [comment]
> Ah yeah mima is mad. We could update the base mima version to 0.16.1?

Yup. Go ahead

**Comment by daddykotex** [comment]
> > Ah yeah mima is mad. We could update the base mima version to 0.16.1?
> 
> Yup. Go ahead

I had to tweak the settings a bit:

* when a patch is present, we exclude published versions that have a patch inferior to it
* when it's not there we keep all versions

**Review by lewisjkl — APPROVED** [review]
🤌

**Comment by daddykotex** [comment]
> > > Ah yeah mima is mad. We could update the base mima version to 0.16.1?
> > 
> > 
> > Yup. Go ahead
> 
> I had to tweak the settings a bit:
> 
> * when a patch is present, we exclude published versions that have a patch inferior to it
> * when it's not there we keep all versions

It's rather hard to test but I tested it locally by creating tags and playing with the sbt version, I am confident.

**Pull request merged**
