### PR TITLE
perf: Optimize isRecursive check in DynamicModelCompiler

### LINKED ISSUE #1258: `DynamicSchemaIndex.loadModel` is slow
On my machine (M1 Max MBP), loading a relatively large model (15k+ shapes) takes less than a second on the Smithy (aws) side but over 11 seconds on the `DynamicSchemaIndex`side.

You can try yourself (with granular steps) with the following scala-cli script:

```scala
//> using lib "com.disneystreaming.smithy4s::smithy4s-dynamic:0.18.2"
//> using lib "io.get-coursier:coursier_2.13:2.1.7"
//> using scala "3.3.1"
//> using toolkit "latest"
//> using option "-Wunused:imports"
import coursier._
import coursier.parse.DependencyParser
import smithy4s.Document
import smithy4s.dynamic.DynamicSchemaIndex
import smithy4s.dynamic.NodeToDocument
import software.amazon.smithy.model.Model
import software.amazon.smithy.model.shapes.ModelSerializer
import software.amazon.smithy.model.transform.ModelTransformer
import scala.concurrent.ExecutionContext

def measure[A](tag: String)(f: => A): A = {
  val start = System.nanoTime()
  val result = f
  println(s"$tag: ${(System.nanoTime() - start) / 1000000}ms")
  result
}

@main def main = {

  val jars = measure("fetch jars") {
    Fetch()
      .withDependencies(
        List(
          "aws-quicksight-spec",
          "aws-sagemaker-spec"
        ).takeRight(3)
          .map { sdk =>
            DependencyParser
              .dependency(
                s"com.disneystreaming.smithy:$sdk:2023.09.22",
                "2.13"
              )
              .toOption
              .get
          }
      )
      .run()(ExecutionContext.global)
      // poor man's way of filtering out jars without a smithy manifest. don't judge pls
      .filterNot(_.toString().contains("smithy-model"))
      .filterNot(_.toString().contains("smithy-jmespath"))
      .filterNot(_.toString().contains("smithy-utils"))
  }

  val model = measure("load model") {
    val assembler = Model
      .assembler()

    jars.foreach(jar => assembler.addImport(jar.toURI().toURL()))

    assembler
      .assemble()
      .unwrap()
  }

  println(model.shapes().toList().size() + " shapes")

  val codec = measure("derive codec") {
    Document.decoderFromSchema[smithy4s.dynamic.model.Model]
  }

  // the equivalent of loadModel's first part
  val converted = measure("convert model") {
    val flattenedModel =
      ModelTransformer.create().flattenAndRemoveMixins(model);
    val node = ModelSerializer.builder().build.serialize(flattenedModel)
    val document = NodeToDocument(node)

    codec.decode(document).toTry.get
  }

  measure("load dsi") { DynamicSchemaIndex.load(converted) }
}

```

Here are the timings:

```
fetch jars: 359ms
load model: 624ms
15545 shapes
derive codec: 75ms
convert model: 281ms
load dsi: 11174ms
```

### NOTE: some models are not like the others

The characteristics of a model, e.g. how deep vs how wide the shapes are, may have an impact on the timings here. The profiles described below come from distinct models that may or may not have similar depths.

### Optimizing recursiveness checks

First, I wanted to show a profiler run on a confidential model with, apparently, deep shape closures.

I ran a profiler during `load dsi` and it turns out that the biggest culprit, taking over 70% of the entire `load` call, are recursion checks:

image

Perhaps there's a more efficient way of performing such checks. I haven't seen the code, but `transitiveClosure` may be trying to do too much (i.e. collecting all shapes into a large set, rather than recursing until a known `ShapeId` is found).

---

Now here's the flame graph for the AWS model made from the specs in the snippet above:

image

Zoomed in:

image

`isRecursive` takes up 86% of the whole thing, again. I think if we can optimize that part, we can save a lot of time on loading dynamic models in general.

#### Extra info

I checked `isRecursive` for any outliers and it appears that only a dozen of shapes (out of thousands) take over 500ms to check:

```
Warning: took 603 ms to compile com.amazonaws.quicksight#AnalysisDefinition
Warning: took 563 ms to compile com.amazonaws.quicksight#CreateAnalysisRequest
Warning: took 588 ms to compile com.amazonaws.quicksight#CreateDashboardRequest
Warning: took 572 ms to compile com.amazonaws.quicksight#CreateTemplateRequest
Warning: took 560 ms to compile com.amazonaws.quicksight#DashboardVersionDefinition
Warning: took 520 ms to compile com.amazonaws.quicksight#DescribeAnalysisDefinitionResponse
Warning: took 518 ms to compile com.amazonaws.quicksight#DescribeDashboardDefinitionResponse
Warning: took 520 ms to compile com.amazonaws.quicksight#DescribeTemplateDefinitionResponse
Warning: took 504 ms to compile com.amazonaws.quicksight#SheetDefinition
```

which suggests that they're extra deep/wide, but I haven't checked that yet.

I also checked what happens if we rewrite `isRecursive` to be more lazy and return as soon as the current shape is seen (note: didn't check for correctness):

```scala
private def isRecursive(
    id: ShapeId
): Boolean = measureIfSlow(id.toString) {
  def transitiveClosureContainsSelf(
      _id: ShapeId,
      visited: Set[ShapeId]
  ): Boolean = {
    val neighbours = closureMap.getOrElse(_id, Set.empty)

    if (neighbours.contains(id)) true
    else {
      val newVisited = visited + _id

      neighbours.iterator
        .filterNot(newVisited)
        .exists(
          transitiveClosureContainsSelf(_, newVisited)
        )
    }
  }

  transitiveClosureContainsSelf(id, Set.empty)
}
```

It didn't help much:

```
Warning: took 622 ms to compile com.amazonaws.quicksight#AnalysisDefinition
Warning: took 575 ms to compile com.amazonaws.quicksight#CreateAnalysisRequest
Warning: took 583 ms to compile com.amazonaws.quicksight#CreateDashboardRequest
Warning: took 576 ms to compile com.amazonaws.quicksight#CreateTemplateRequest
Warning: took 576 ms to compile com.amazonaws.quicksight#DashboardVersionDefinition
Warning: took 575 ms to compile com.amazonaws.quicksight#DescribeAnalysisDefinitionResponse
Warning: took 579 ms to compile com.amazonaws.quicksight#DescribeDashboardDefinitionResponse
Warning: took 572 ms to compile com.amazonaws.quicksight#DescribeTemplateDefinitionResponse
Warning: took 562 ms to compile com.amazonaws.quicksight#SheetDefinition
Warning: took 578 ms to compile com.amazonaws.quicksight#TemplateVersionDefinition
Warning: took 574 ms to compile com.amazonaws.quicksight#UpdateAnalysisRequest
Warning: took 577 ms to compile com.amazonaws.quicksight#UpdateDashboardRequest
Warning: took 579 ms to compile com.amazonaws.quicksight#UpdateTemplateRequest
Warning: took 551 ms to compile com.amazonaws.quicksight#Visual
load dsi: 12052ms
```

and neither did caching or a combination of the two. I'm hoping that it's just a mistake on my side and the closure check can still be optimized.

### PR DESCRIPTION
**Pull request by ghostbuster91**
This fixes #1258 

`DynamicSchemaIndex.load` times before and after this change for some models tested on Intel® Core™ i7-10875H × 16 64GB RAM. Testing script was mostly based on the one from the [issue](https://github.com/disneystreaming/smithy4s/issues/1258#issue-1938852215).

A model that consists of "aws-quicksight-spec" and "aws-sagemaker-spec".
- before: 17 675ms
- after: 2 659ms
- flamegraph after:flamegraph3

A confidential model:
- before: 12 821ms
- after: 2 472ms
- flamegraph after: flamegraph2

The new implementation has been tested manually with mentioned models against the old one and they both return the same results; however, it should be noted that the first model contains only a single recursive shape, while the confidential model contains only a few more.

The implementation is fully based on @Baccata's [idea](https://github.com/disneystreaming/smithy4s/issues/1258#issuecomment-1759187608). My plan was to check that approach and then move to implementing mentioned Tarjan algorithm, but this implementation turned out to be quite fast. I don't mind implementing Tarjan but I propose to stop here, as at the moment the current solution is fast enough. Implementing Tarjan would probably yield better results but I think that the increase in complexity outweighs potential gains in speed. This decision can always be revisited in the future if needed.

## PR Checklist (not all items are relevant to all PRs)

- [x] Added unit-tests (for runtime code)
- [ ] Added bootstrapped code + smoke tests (when the rendering logic is modified)
- [ ] Added build-plugins integration tests (when reflection loading is required at codegen-time)
- [ ] Added alloy compliance tests (when simpleRestJson protocol behaviour is expanded/updated)
- [ ] Updated dynamic module to match generated-code behaviour
- [ ] Added documentation
- [ ] Updated changelog

### CODE REVIEW

**Review by Baccata — APPROVED** [review]

**Comment by Baccata** [comment]
@ghostbuster91, if it's not too much to ask, would you mind applying the same logic to the codegen side of things when you have a little time ? It may help the build-time when generating code from big models

**Comment by kubukoz** [comment]
Probably a good idea to run some profiling first as well, it's possible there are other bottlenecks in there

**Comment by kubukoz** [comment]
I made a separate ticket for the codegen part so that it's easier to track and discuss on its own: https://github.com/disneystreaming/smithy4s/issues/1483

**Comment by ghostbuster91** [comment]
Thanks @kubukoz 
@Baccata sorry for not responding earlier - it's been a tough week. Sure, I can take a look at it, probably next week.

**Pull request merged**
