### PR TITLE
Enable Mima Checks

### PR DESCRIPTION
**Pull request by lewisjkl**
Enables Mima Checks on the following modules (all variants of scala versions/CE versions)

- json
- http4s
- core

### CODE REVIEW

**Comment by daddykotex** [comment]
We're seeing:  ` http4s: mimaPreviousArtifacts is empty, not analyzing binary compatibility.` I'm assuming this is normal, since w'ere just enabling it


<summary>Full logs
 <details>

```
[info] [coreNative3] compiling 199 Scala sources to /home/runner/work/smithy4s/smithy4s/modules/core/target/native-3/classes ...
[info] [coreJS] compiling 198 Scala sources to /home/runner/work/smithy4s/smithy4s/modules/core/target/js-2.13/classes ...
[info] [coreJS] done compiling
[info] [core3] compiling 199 Scala sources to /home/runner/work/smithy4s/smithy4s/modules/core/target/jvm-3/classes ...
[info] [coreNative3] done compiling
[info] [coreJS3] compiling 198 Scala sources to /home/runner/work/smithy4s/smithy4s/modules/core/target/js-3/classes ...
[info] [core3] done compiling
[info] [coreJS] core: mimaPreviousArtifacts is empty, not analyzing binary compatibility.
[info] [json] compiling 6 Scala sources to /home/runner/work/smithy4s/smithy4s/modules/json/target/jvm-2.13/classes ...
[info] [json] done compiling
[info] [coreNative3] core: mimaPreviousArtifacts is empty, not analyzing binary compatibility.
[info] [coreJS3] done compiling
[info] [jsonJS] compiling 6 Scala sources to /home/runner/work/smithy4s/smithy4s/modules/json/target/js-2.13/classes ...
[info] [jsonJS] done compiling
[info] [jsonNative3] compiling 6 Scala sources to /home/runner/work/smithy4s/smithy4s/modules/json/target/native-3/classes ...
[info] [jsonNative3] done compiling
[info] [json3] compiling 6 Scala sources to /home/runner/work/smithy4s/smithy4s/modules/json/target/jvm-3/classes ...
[info] [coreJS3] core: mimaPreviousArtifacts is empty, not analyzing binary compatibility.
[info] [http4s2_12] compiling 9 Scala sources to /home/runner/work/smithy4s/smithy4s/modules/http4s/target/ce3-jvm-2.12/classes ...
[info] [json3] done compiling
[info] [jsonJS] json: mimaPreviousArtifacts is empty, not analyzing binary compatibility.
[info] [http4s_CE2] compiling 9 Scala sources to /home/runner/work/smithy4s/smithy4s/modules/http4s/target/ce2-jvm-2.13/classes ...
[info] [http4s_CE2] done compiling
[info] [http4s] compiling 9 Scala sources to /home/runner/work/smithy4s/smithy4s/modules/http4s/target/ce3-jvm-2.13/classes ...
[info] [http4s] done compiling
[info] [jsonJS3] compiling 6 Scala sources to /home/runner/work/smithy4s/smithy4s/modules/json/target/js-3/classes ...
[info] [jsonJS3] done compiling
[info] [jsonNative3] json: mimaPreviousArtifacts is empty, not analyzing binary compatibility.
[info] [http4sJS] compiling 9 Scala sources to /home/runner/work/smithy4s/smithy4s/modules/http4s/target/ce3-js-2.13/classes ...
[info] [http4s2_12] done compiling
[info] [jsonJS3] json: mimaPreviousArtifacts is empty, not analyzing binary compatibility.
[info] [http4s3] compiling 9 Scala sources to /home/runner/work/smithy4s/smithy4s/modules/http4s/target/ce3-jvm-3/classes ...
[info] [http4sJS] done compiling
[info] [http4sJS3] compiling 9 Scala sources to /home/runner/work/smithy4s/smithy4s/modules/http4s/target/ce3-js-3/classes ...
[info] [http4s3] done compiling
[info] [http4sJS] http4s: mimaPreviousArtifacts is empty, not analyzing binary compatibility.
[info] [http4sJS3] done compiling
[info] [http4sJS3] http4s: mimaPreviousArtifacts is empty, not analyzing binary compatibility.
```

</details>
</summary>

**Comment by lewisjkl** [comment]
You'll notice that line is only showing up for JS or native modules. These ones aren't checked since it only works on JVM
CleanShot 2022-08-23 at 13 39 45

**Comment by daddykotex** [comment]
Ok, thanks for clearing that out

**Review by daddykotex — APPROVED** [review]

**Comment by armanbilge** [comment]
> These ones aren't checked since it only works on JVM

This is a common misconception. MiMa works perfectly fine for JS and Native as well (check any Typelevel project to see for yourself :)

**Comment by lewisjkl** [comment]
> This is a common misconception. MiMa works perfectly fine for JS and Native as well (check any Typelevel project to see for yourself :)

Ah TIL, thanks for the info. I just added a new PR to enable it on JS and Native: #415

**Pull request merged**
