### PR TITLE
Remove unsupported resource note

### PR DESCRIPTION
**Pull request by kubukoz**

### CODE REVIEW

**Comment by Baccata** [comment]
I think it'd be good to have a description of how resources are handled, rather than just removing it altogether

**Comment by kubukoz** [comment]
Fair point. Will amend

**Comment by zetashift** [comment]
How about something like:

```
Smithy has a `resource` type of shape, that represents CRUD specialized services. Smithy4s only transitively transfers the operations defined in a `resource` to the service that lists that `resource`.
```

**Comment by Baccata** [comment]
I like it 😄

**Comment by Baccata** [comment]
Closing in favour of https://github.com/disneystreaming/smithy4s/pull/825. Thanks @zetashift !

**Pull request closed without merging**
