### PR TITLE
Keep protocol in smithy4s->http4s URI conversion

### LINKED ISSUE #1232: Strange behavior in http4s URIs
In this code:

```scala
//> using lib "com.disneystreaming.smithy4s::smithy4s-http4s:0.17.19"
import cats.effect.unsafe.IORuntime
import cats.effect.IO

import org.http4s.client.Client
import demo.DemoGen
import smithy4s.http4s.SimpleRestJsonBuilder
import demo.Demo
import org.http4s.Response
import cats.effect.kernel.Resource
import cats.implicits._
import cats.effect.implicits._

val c: Client[IO] = Client { req =>

  IO.println(req.uri).toResource *>
    Resource.pure(Response())
}

@main def run =
  SimpleRestJsonBuilder(Demo)
    .client(c)
    .make
    .toTry
    .get
    .getDemo()
    .unsafeRunSync()(IORuntime.global)
```

In 0.17.19, the captured URI is:

```
http://localhost:8080/demo
```

However, on the latest series/0.18 snapshot:

```scala
//localhost:8080/demo
```

That doesn't seem like a valid URL. I think we should dig into it before 0.18 hits shelves.

### PR DESCRIPTION
**Pull request by kubukoz**
Closes #1232

### CODE REVIEW

**Comment by kubukoz** [comment]
Something else I'm wondering about:

```scala
    val uriScheme = uri.scheme match {
      case Some(Uri.Scheme.http) => Smithy4sHttpUriScheme.Http
      case _                     => Smithy4sHttpUriScheme.Https
    }
```

this would make `https` the default scheme. I'm not sure we're ready for such a revolution... but it certainly would be worth at least documenting somewhere.

**Comment by daddykotex** [comment]
> Something else I'm wondering about:
> 
> ```scala
>     val uriScheme = uri.scheme match {
>       case Some(Uri.Scheme.http) => Smithy4sHttpUriScheme.Http
>       case _                     => Smithy4sHttpUriScheme.Https
>     }
> ```
> 
> this would make `https` the default scheme. I'm not sure we're ready for such a revolution... but it certainly would be worth at least documenting somewhere.

I'd also do the opposite, match if we have `Some(https)` and use `http` otherwise

**Review by daddykotex — APPROVED** [review]
Thanks

**Review by Baccata — APPROVED** [review]
Thanks !

**Pull request merged**
