### PR TITLE
Implement SchemaVisitorJCodec

### PR DESCRIPTION
**Pull request by daddykotex**
Please review commit by commit, but be aware:
1. not all commit compile/run, I went very granular to help with review
1. I did a `git mv` in one of the last commit but I think git still sees the file as a new file / deleted file

important remarks:
1. question: `def set` use `def expecting: String = "list"` and use `vectors` in error message, should we update that?
1. note: union* method use the whole alternative vector as argument rather than first and rest
1. called to .hints instead of .instance.hints in some place to fix the build

### CODE REVIEW

**Comment by daddykotex** [comment]
For example, one commit's diff: https://github.com/disneystreaming/smithy4s/pull/270/commits/eda5d47024cafc8b21ab9a3bed35cc4e27feef04

**Comment by Baccata** [comment]
One thing that's missing and that doesn't seem to have been caught by tests is that the hints on fields and alternatives must be added to the schema before the recursive call to `apply`. 

In other words, if you have something like 

```
structure Foo {
   @range(min: 1) 
   bar: Integer
} 
```

the constraint is not checked for. 

In all frankness, I think it might be indicative of a design mistake on my end on the `Schema` construct ... having to remember this is a burden for implementors. I should probably revert that particular decision

**Comment by Baccata** [comment]
Also, would you mind running jsoniter's benchmarks (smithy4s only, before/after) to check nothing has drastically changed.

**Comment by Baccata** [comment]
@daddykotex sorry, I meant the benchmarks added by Andriy in jsoniter. See https://github.com/plokhotnyuk/jsoniter-scala/pull/903.

**Comment by daddykotex** [comment]
I ran the same benchmarks as the one in the linked issue:

```
[info] Benchmark                            Mode  Cnt        Score        Error  Units
[info] PrimitivesReading.avSystemGenCodec  thrpt    5  1964791.056 ±  62726.444  ops/s
[info] PrimitivesReading.borer             thrpt    5  3554098.056 ± 177032.829  ops/s
[info] PrimitivesReading.circe             thrpt    5  1576861.789 ±   7304.111  ops/s
[info] PrimitivesReading.circeJawn         thrpt    5  1483764.032 ± 119817.340  ops/s
[info] PrimitivesReading.circeJsoniter     thrpt    5  1907346.680 ±  25161.666  ops/s
[info] PrimitivesReading.dslJsonScala      thrpt    5  6004786.747 ± 502493.313  ops/s
[info] PrimitivesReading.jacksonScala      thrpt    5  2977050.834 ±  23591.477  ops/s
[info] PrimitivesReading.jsoniterScala     thrpt    5  9592147.047 ±  87364.483  ops/s
[info] PrimitivesReading.playJson          thrpt    5   939943.657 ±   2699.089  ops/s
[info] PrimitivesReading.playJsonJsoniter  thrpt    5  1488974.516 ±   5021.621  ops/s
[info] PrimitivesReading.smithy4sJson      thrpt    5  1579419.669 ±  24745.381  ops/s
[info] PrimitivesReading.sprayJson         thrpt    5  1344518.419 ±  17773.342  ops/s
[info] PrimitivesReading.uPickle           thrpt    5  2302199.476 ±  24383.902  ops/s
[info] PrimitivesReading.weePickle         thrpt    5  3122751.644 ±  54852.888  ops/s
[info] PrimitivesReading.zioJson           thrpt    5  2261862.967 ±  19296.745  ops/s
[info] PrimitivesWriting.avSystemGenCodec       thrpt    5   2932702.835 ± 152187.114  ops/s
[info] PrimitivesWriting.borer                  thrpt    5   5479699.505 ± 158256.171  ops/s
[info] PrimitivesWriting.circe                  thrpt    5   2108365.262 ±   9930.262  ops/s
[info] PrimitivesWriting.circeJsoniter          thrpt    5   3238673.130 ±  30657.005  ops/s
[info] PrimitivesWriting.dslJsonScala           thrpt    5   4248865.923 ± 102504.284  ops/s
[info] PrimitivesWriting.jacksonScala           thrpt    5   3994637.004 ±  17401.980  ops/s
[info] PrimitivesWriting.jsoniterScala          thrpt    5  30849549.534 ± 217909.797  ops/s
[info] PrimitivesWriting.jsoniterScalaPrealloc  thrpt    5  34047320.171 ± 223904.416  ops/s
[info] PrimitivesWriting.playJson               thrpt    5    589982.167 ±   3460.039  ops/s
[info] PrimitivesWriting.playJsonJsoniter       thrpt    5    688027.661 ±   3122.165  ops/s
[info] PrimitivesWriting.smithy4sJson           thrpt    5   8373065.422 ±  90376.681  ops/s
[info] PrimitivesWriting.sprayJson              thrpt    5   1877675.357 ±   8061.768  ops/s
[info] PrimitivesWriting.uPickle                thrpt    5   2813648.849 ±  55898.553  ops/s
[info] PrimitivesWriting.weePickle              thrpt    5   3643981.034 ±  18601.522  ops/s
[info] PrimitivesWriting.zioJson                thrpt    5   2736673.146 ±  65647.823  ops/s
```

```
[info] Benchmark                                   (size)   Mode  Cnt        Score       Error  Units
[info] NestedStructsReading.avSystemGenCodec          128  thrpt    5    73610.895 ±  2635.743  ops/s
[info] NestedStructsReading.circe                     128  thrpt    5    90538.178 ±  2210.264  ops/s
[info] NestedStructsReading.circeJawn                 128  thrpt    5    88986.286 ±  1031.419  ops/s
[info] NestedStructsReading.circeJsoniter             128  thrpt    5   104268.413 ±   685.171  ops/s
[info] NestedStructsReading.dslJsonScala              128  thrpt    5   296481.539 ±  7851.665  ops/s
[info] NestedStructsReading.jacksonScala              128  thrpt    5   133399.415 ±  3738.873  ops/s
[info] NestedStructsReading.jsoniterScala             128  thrpt    5   522116.111 ±  5768.170  ops/s
[info] NestedStructsReading.playJson                  128  thrpt    5    41056.825 ±  1251.927  ops/s
[info] NestedStructsReading.playJsonJsoniter          128  thrpt    5    64903.111 ±   550.909  ops/s
[info] NestedStructsReading.smithy4sJson              128  thrpt    5    82873.214 ±   703.152  ops/s
[info] NestedStructsReading.sprayJson                 128  thrpt    5   197767.235 ±   708.737  ops/s
[info] NestedStructsReading.uPickle                   128  thrpt    5   155483.773 ±   913.979  ops/s
[info] NestedStructsReading.weePickle                 128  thrpt    5   165458.075 ±  2610.581  ops/s
[info] NestedStructsWriting.avSystemGenCodec          128  thrpt    5   306207.475 ±  1480.077  ops/s
[info] NestedStructsWriting.circe                     128  thrpt    5    80055.679 ±   725.135  ops/s
[info] NestedStructsWriting.circeJsoniter             128  thrpt    5   131678.406 ±  1072.679  ops/s
[info] NestedStructsWriting.jacksonScala              128  thrpt    5   186576.963 ±  1253.498  ops/s
[info] NestedStructsWriting.jsoniterScala             128  thrpt    5  1255305.199 ± 26453.738  ops/s
[info] NestedStructsWriting.jsoniterScalaPrealloc     128  thrpt    5  1289259.185 ±  6592.928  ops/s
[info] NestedStructsWriting.playJson                  128  thrpt    5    69987.569 ±   158.296  ops/s
[info] NestedStructsWriting.playJsonJsoniter          128  thrpt    5    63991.338 ±   529.037  ops/s
[info] NestedStructsWriting.smithy4sJson              128  thrpt    5   365560.189 ±  4549.632  ops/s
[info] NestedStructsWriting.sprayJson                 128  thrpt    5    85067.053 ±  1467.370  ops/s
[info] NestedStructsWriting.uPickle                   128  thrpt    5   156400.136 ±  1567.786  ops/s
[info] NestedStructsWriting.weePickle                 128  thrpt    5   246109.328 ±  4213.073  ops/s
```

```
[info] Benchmark                                           Mode  Cnt       Score      Error  Units
[info] GoogleMapsAPIPrettyPrinting.avSystemGenCodec       thrpt    5   20606.417 ± 1348.730  ops/s
[info] GoogleMapsAPIPrettyPrinting.circe                  thrpt    5   18775.077 ±  697.807  ops/s
[info] GoogleMapsAPIPrettyPrinting.circeJsoniter          thrpt    5   23905.364 ±   78.719  ops/s
[info] GoogleMapsAPIPrettyPrinting.jacksonScala           thrpt    5   27656.551 ±  129.606  ops/s
[info] GoogleMapsAPIPrettyPrinting.jsoniterScala          thrpt    5   72752.117 ±  783.834  ops/s
[info] GoogleMapsAPIPrettyPrinting.jsoniterScalaPrealloc  thrpt    5   78959.527 ± 1588.486  ops/s
[info] GoogleMapsAPIPrettyPrinting.playJson               thrpt    5    7412.766 ±   84.471  ops/s
[info] GoogleMapsAPIPrettyPrinting.playJsonJsoniter       thrpt    5   10713.787 ±  100.584  ops/s
[info] GoogleMapsAPIPrettyPrinting.smithy4sJson           thrpt    5   43918.943 ±  297.767  ops/s
[info] GoogleMapsAPIPrettyPrinting.sprayJson              thrpt    5   14231.000 ±  226.688  ops/s
[info] GoogleMapsAPIPrettyPrinting.uPickle                thrpt    5   25422.501 ±  226.677  ops/s
[info] GoogleMapsAPIPrettyPrinting.weePickle              thrpt    5   24362.821 ±  803.317  ops/s
[info] GoogleMapsAPIPrettyPrinting.zioJson                thrpt    5   20700.079 ±   99.308  ops/s
[info] GoogleMapsAPIReading.avSystemGenCodec              thrpt    5   10502.027 ±  151.035  ops/s
[info] GoogleMapsAPIReading.borer                         thrpt    5   28121.280 ±   50.922  ops/s
[info] GoogleMapsAPIReading.circe                         thrpt    5    7762.587 ±   70.984  ops/s
[info] GoogleMapsAPIReading.circeJawn                     thrpt    5   11271.154 ±  353.495  ops/s
[info] GoogleMapsAPIReading.circeJsoniter                 thrpt    5   20007.317 ±  128.273  ops/s
[info] GoogleMapsAPIReading.dslJsonScala                  thrpt    5   20860.590 ±   74.075  ops/s
[info] GoogleMapsAPIReading.jacksonScala                  thrpt    5   24852.206 ±  100.862  ops/s
[info] GoogleMapsAPIReading.jsoniterScala                 thrpt    5   48796.465 ± 1444.371  ops/s
[info] GoogleMapsAPIReading.ninnyJson                     thrpt    5   10071.662 ±  308.159  ops/s
[info] GoogleMapsAPIReading.playJson                      thrpt    5    8518.251 ±   56.694  ops/s
[info] GoogleMapsAPIReading.playJsonJsoniter              thrpt    5   16074.081 ± 1141.868  ops/s
[info] GoogleMapsAPIReading.smithy4sJson                  thrpt    5   15477.374 ±  478.828  ops/s
[info] GoogleMapsAPIReading.sprayJson                     thrpt    5   13358.847 ±   64.817  ops/s
[info] GoogleMapsAPIReading.uPickle                       thrpt    5    9797.737 ±   98.862  ops/s
[info] GoogleMapsAPIReading.weePickle                     thrpt    5   21415.239 ±  795.802  ops/s
[info] GoogleMapsAPIReading.zioJson                       thrpt    5   12036.041 ±  355.713  ops/s
[info] GoogleMapsAPIWriting.avSystemGenCodec              thrpt    5   34557.249 ±  885.394  ops/s
[info] GoogleMapsAPIWriting.borer                         thrpt    5   36595.028 ±  574.460  ops/s
[info] GoogleMapsAPIWriting.circe                         thrpt    5   18765.814 ±  212.937  ops/s
[info] GoogleMapsAPIWriting.circeJsoniter                 thrpt    5   26911.908 ± 1312.935  ops/s
[info] GoogleMapsAPIWriting.dslJsonScala                  thrpt    5   63879.767 ± 1946.377  ops/s
[info] GoogleMapsAPIWriting.jacksonScala                  thrpt    5   65828.283 ±  823.303  ops/s
[info] GoogleMapsAPIWriting.jsoniterScala                 thrpt    5  106475.929 ±  813.791  ops/s
[info] GoogleMapsAPIWriting.jsoniterScalaPrealloc         thrpt    5   87896.006 ±  326.698  ops/s
[info] GoogleMapsAPIWriting.ninnyJson                     thrpt    5   15151.241 ±  421.469  ops/s
[info] GoogleMapsAPIWriting.playJson                      thrpt    5    8286.082 ±   87.734  ops/s
[info] GoogleMapsAPIWriting.playJsonJsoniter              thrpt    5   11679.330 ±  108.614  ops/s
[info] GoogleMapsAPIWriting.smithy4sJson                  thrpt    5   47204.231 ±  396.671  ops/s
[info] GoogleMapsAPIWriting.sprayJson                     thrpt    5   21264.744 ±   87.230  ops/s
[info] GoogleMapsAPIWriting.uPickle                       thrpt    5   33882.589 ± 1410.244  ops/s
[info] GoogleMapsAPIWriting.weePickle                     thrpt    5   47673.430 ±  535.408  ops/s
[info] GoogleMapsAPIWriting.zioJson                       thrpt    5   31226.351 ±  261.614  ops/s
```

There does not seem to be any regression, but I'm running this on a M1 which is quite different from what @plokhotnyuk used on his PR I guess.

**Comment by daddykotex** [comment]
> You can probably pass a glob filter to the jmh command to only run the smithy4s ones

Yeah, I was not able to do it until now. That's why I initially went the easy route and ran the same one from the PR. Will update with a before and after for `.*.smithy4sJson`

**Comment by daddykotex** [comment]
Before:

```
[info] Benchmark                                  (size)   Mode  Cnt         Score        Error  Units
[info] ADTReading.smithy4sJson                       N/A  thrpt    5   2398176.220 ± 108303.195  ops/s
[info] ADTWriting.smithy4sJson                       N/A  thrpt    5   8437056.427 ±  85618.111  ops/s
[info] AnyValsReading.smithy4sJson                   N/A  thrpt    5   1959856.080 ±  29909.431  ops/s
[info] AnyValsWriting.smithy4sJson                   N/A  thrpt    5   8294473.824 ±  78167.130  ops/s
[info] ArrayOfBigDecimalsReading.smithy4sJson        128  thrpt    5    118015.048 ±   3855.693  ops/s
[info] ArrayOfBigDecimalsWriting.smithy4sJson        128  thrpt    5     82763.207 ±   1157.593  ops/s
[info] ArrayOfBigIntsReading.smithy4sJson            128  thrpt    5    161741.955 ±   7885.542  ops/s
[info] ArrayOfBigIntsWriting.smithy4sJson            128  thrpt    5     84357.276 ±   2622.033  ops/s
[info] ArrayOfBooleansReading.smithy4sJson           128  thrpt    5    303122.174 ±   2932.675  ops/s
[info] ArrayOfBooleansWriting.smithy4sJson           128  thrpt    5   1888649.419 ±  72666.724  ops/s
[info] ArrayOfBytesReading.smithy4sJson              128  thrpt    5    302592.700 ±   2923.858  ops/s
[info] ArrayOfBytesWriting.smithy4sJson              128  thrpt    5   1794201.254 ±   8833.376  ops/s
[info] ArrayOfDoublesReading.smithy4sJson            128  thrpt    5    204587.240 ±   2703.395  ops/s
[info] ArrayOfDoublesWriting.smithy4sJson            128  thrpt    5    216337.568 ±   3035.676  ops/s
[info] ArrayOfFloatsReading.smithy4sJson             128  thrpt    5    264770.635 ±   7574.607  ops/s
[info] ArrayOfFloatsWriting.smithy4sJson             128  thrpt    5    315041.260 ±   7335.917  ops/s
[info] ArrayOfInstantsReading.smithy4sJson           128  thrpt    5     12838.048 ±    452.895  ops/s
[info] ArrayOfInstantsWriting.smithy4sJson           128  thrpt    5     27186.557 ±    863.173  ops/s
[info] ArrayOfIntsReading.smithy4sJson               128  thrpt    5    263572.742 ±   2593.068  ops/s
[info] ArrayOfIntsWriting.smithy4sJson               128  thrpt    5    938403.109 ±  23404.162  ops/s
[info] ArrayOfLongsReading.smithy4sJson              128  thrpt    5    284957.780 ±   2817.141  ops/s
[info] ArrayOfLongsWriting.smithy4sJson              128  thrpt    5    588794.292 ±  33077.645  ops/s
[info] ArrayOfShortsReading.smithy4sJson             128  thrpt    5    283114.738 ±   3241.466  ops/s
[info] ArrayOfShortsWriting.smithy4sJson             128  thrpt    5   1405148.337 ±   3876.207  ops/s
[info] ArrayOfUUIDsReading.smithy4sJson              128  thrpt    5    136821.873 ±   1970.442  ops/s
[info] ArrayOfUUIDsWriting.smithy4sJson              128  thrpt    5    672070.895 ±   8401.650  ops/s
[info] Base64Reading.smithy4sJson                    128  thrpt    5   7875488.522 ± 101169.238  ops/s
[info] Base64Writing.smithy4sJson                    128  thrpt    5  10108998.119 ± 123852.620  ops/s
[info] BigDecimalWriting.smithy4sJson                128  thrpt    5    759872.675 ±  31113.731  ops/s
[info] BigIntReading.smithy4sJson                    128  thrpt    5   7779281.645 ± 123254.088  ops/s
[info] BigIntWriting.smithy4sJson                    128  thrpt    5    678839.809 ±  13162.155  ops/s
[info] ExtractFieldsReading.smithy4sJson             128  thrpt    5    152352.480 ±   2736.498  ops/s
[info] GeoJSONReading.smithy4sJson                   N/A  thrpt    5     23118.274 ±    173.196  ops/s
[info] GeoJSONWriting.smithy4sJson                   N/A  thrpt    5     20753.572 ±   1199.680  ops/s
[info] GitHubActionsAPIReading.smithy4sJson          N/A  thrpt    5    172020.411 ±   1390.046  ops/s
[info] GitHubActionsAPIWriting.smithy4sJson          N/A  thrpt    5    474886.344 ±  18327.983  ops/s
[info] GoogleMapsAPIPrettyPrinting.smithy4sJson      N/A  thrpt    5     41090.444 ±    463.633  ops/s
[info] GoogleMapsAPIReading.smithy4sJson             N/A  thrpt    5     16884.089 ±    260.824  ops/s
[info] GoogleMapsAPIWriting.smithy4sJson             N/A  thrpt    5     50990.538 ±    468.921  ops/s
[info] IntReading.smithy4sJson                       N/A  thrpt    5  57238862.853 ± 738785.297  ops/s
[info] IntWriting.smithy4sJson                       N/A  thrpt    5  48923954.353 ± 797891.915  ops/s
[info] ListOfBooleansReading.smithy4sJson            128  thrpt    5    354608.040 ±   5260.778  ops/s
[info] ListOfBooleansWriting.smithy4sJson            128  thrpt    5   2632389.648 ±  36261.687  ops/s
[info] MapOfIntsToBooleansReading.smithy4sJson       128  thrpt    5    120646.992 ±    735.708  ops/s
[info] MapOfIntsToBooleansWriting.smithy4sJson       128  thrpt    5    652794.469 ±  12557.574  ops/s
[info] MissingRequiredFieldsReading.smithy4sJson     N/A  thrpt    5   5281958.439 ± 115578.785  ops/s
[info] NestedStructsReading.smithy4sJson             128  thrpt    5     96460.334 ±   1944.129  ops/s
[info] NestedStructsWriting.smithy4sJson             128  thrpt    5    380156.696 ±   4613.754  ops/s
[info] OpenRTBReading.smithy4sJson                   N/A  thrpt    5    187514.571 ±   1350.416  ops/s
[info] OpenRTBWriting.smithy4sJson                   N/A  thrpt    5    353662.159 ±   2329.853  ops/s
[info] PrimitivesReading.smithy4sJson                N/A  thrpt    5   2007980.443 ±  21091.474  ops/s
[info] PrimitivesWriting.smithy4sJson                N/A  thrpt    5   8631353.129 ±  25746.832  ops/s
[info] SetOfIntsReading.smithy4sJson                 128  thrpt    5    115699.910 ±   2709.233  ops/s
[info] SetOfIntsWriting.smithy4sJson                 128  thrpt    5    984885.533 ±   4903.178  ops/s
[info] StringOfAsciiCharsReading.smithy4sJson        128  thrpt    5  15289783.977 ± 134781.651  ops/s
[info] StringOfAsciiCharsWriting.smithy4sJson        128  thrpt    5   6275547.578 ±  57086.814  ops/s
[info] StringOfEscapedCharsReading.smithy4sJson      128  thrpt    5   3415786.949 ± 148413.977  ops/s
[info] StringOfEscapedCharsWriting.smithy4sJson      128  thrpt    5   4141860.014 ±  15138.993  ops/s
[info] StringOfNonAsciiCharsReading.smithy4sJson     128  thrpt    5   3579543.017 ±  21416.760  ops/s
[info] StringOfNonAsciiCharsWriting.smithy4sJson     128  thrpt    5   3132251.030 ±  22949.191  ops/s
[info] TwitterAPIReading.smithy4sJson                N/A  thrpt    5     36879.833 ±    403.007  ops/s
[info] TwitterAPIWriting.smithy4sJson                N/A  thrpt    5     98619.046 ±   3614.063  ops/s
[info] VectorOfBooleansReading.smithy4sJson          128  thrpt    5    302640.060 ±   3472.153  ops/s
[info] VectorOfBooleansWriting.smithy4sJson          128  thrpt    5   1242409.330 ±   8016.772  ops/s
```


After:

```

[info] Benchmark                                  (size)   Mode  Cnt         Score         Error  Units
[info] ADTReading.smithy4sJson                       N/A  thrpt    5   2192986.055 ±   69796.055  ops/s
[info] ADTWriting.smithy4sJson                       N/A  thrpt    5   9147843.442 ±   89417.074  ops/s
[info] AnyValsReading.smithy4sJson                   N/A  thrpt    5   1523794.445 ±   18072.840  ops/s
[info] AnyValsWriting.smithy4sJson                   N/A  thrpt    5   8216562.967 ±  670717.674  ops/s
[info] ArrayOfBigDecimalsReading.smithy4sJson        128  thrpt    5    124568.582 ±    1130.280  ops/s
[info] ArrayOfBigDecimalsWriting.smithy4sJson        128  thrpt    5     85920.801 ±     313.407  ops/s
[info] ArrayOfBigIntsReading.smithy4sJson            128  thrpt    5    170648.766 ±     438.840  ops/s
[info] ArrayOfBigIntsWriting.smithy4sJson            128  thrpt    5     79859.746 ±    1975.276  ops/s
[info] ArrayOfBooleansReading.smithy4sJson           128  thrpt    5    317256.497 ±    3141.909  ops/s
[info] ArrayOfBooleansWriting.smithy4sJson           128  thrpt    5   1919922.819 ±   10379.568  ops/s
[info] ArrayOfBytesReading.smithy4sJson              128  thrpt    5    332181.792 ±    3005.566  ops/s
[info] ArrayOfBytesWriting.smithy4sJson              128  thrpt    5   1753380.343 ±  144820.477  ops/s
[info] ArrayOfDoublesReading.smithy4sJson            128  thrpt    5    222812.949 ±    3506.117  ops/s
[info] ArrayOfDoublesWriting.smithy4sJson            128  thrpt    5    208283.957 ±    2823.135  ops/s
[info] ArrayOfFloatsReading.smithy4sJson             128  thrpt    5    271796.217 ±    4980.277  ops/s
[info] ArrayOfFloatsWriting.smithy4sJson             128  thrpt    5    312308.873 ±    3774.360  ops/s
[info] ArrayOfInstantsReading.smithy4sJson           128  thrpt    5     12846.977 ±     328.487  ops/s
[info] ArrayOfInstantsWriting.smithy4sJson           128  thrpt    5     27691.117 ±     487.461  ops/s
[info] ArrayOfIntsReading.smithy4sJson               128  thrpt    5    313210.254 ±   17347.927  ops/s
[info] ArrayOfIntsWriting.smithy4sJson               128  thrpt    5    932004.126 ±   45867.784  ops/s
[info] ArrayOfLongsReading.smithy4sJson              128  thrpt    5    309755.100 ±    1990.987  ops/s
[info] ArrayOfLongsWriting.smithy4sJson              128  thrpt    5    598461.338 ±    3131.188  ops/s
[info] ArrayOfShortsReading.smithy4sJson             128  thrpt    5    327752.885 ±    1983.215  ops/s
[info] ArrayOfShortsWriting.smithy4sJson             128  thrpt    5   1282167.837 ±   54533.039  ops/s
[info] ArrayOfUUIDsReading.smithy4sJson              128  thrpt    5    195649.477 ±    3457.244  ops/s
[info] ArrayOfUUIDsWriting.smithy4sJson              128  thrpt    5    671052.970 ±    4077.451  ops/s
[info] Base64Reading.smithy4sJson                    128  thrpt    5   7547956.232 ± 1280662.235  ops/s
[info] Base64Writing.smithy4sJson                    128  thrpt    5   9765175.058 ±  670678.193  ops/s
[info] BigDecimalWriting.smithy4sJson                128  thrpt    5    707386.796 ±   15066.719  ops/s
[info] BigIntReading.smithy4sJson                    128  thrpt    5   7711269.635 ±  150767.700  ops/s
[info] BigIntWriting.smithy4sJson                    128  thrpt    5    685549.251 ±   14155.757  ops/s
[info] ExtractFieldsReading.smithy4sJson             128  thrpt    5    146412.366 ±    4449.215  ops/s
[info] GeoJSONReading.smithy4sJson                   N/A  thrpt    5     23217.532 ±     103.562  ops/s
[info] GeoJSONWriting.smithy4sJson                   N/A  thrpt    5     21628.545 ±     882.517  ops/s
[info] GitHubActionsAPIReading.smithy4sJson          N/A  thrpt    5    172817.299 ±    1398.592  ops/s
[info] GitHubActionsAPIWriting.smithy4sJson          N/A  thrpt    5    478474.476 ±   10031.970  ops/s
[info] GoogleMapsAPIPrettyPrinting.smithy4sJson      N/A  thrpt    5     38094.895 ±     529.542  ops/s
[info] GoogleMapsAPIReading.smithy4sJson             N/A  thrpt    5     16819.520 ±     145.982  ops/s
[info] GoogleMapsAPIWriting.smithy4sJson             N/A  thrpt    5     45923.026 ±    1942.469  ops/s
[info] IntReading.smithy4sJson                       N/A  thrpt    5  57237110.663 ±  528113.481  ops/s
[info] IntWriting.smithy4sJson                       N/A  thrpt    5  48545529.879 ± 1681527.083  ops/s
[info] ListOfBooleansReading.smithy4sJson            128  thrpt    5    356264.198 ±    4555.405  ops/s
[info] ListOfBooleansWriting.smithy4sJson            128  thrpt    5   2633806.317 ±   42024.375  ops/s
[info] MapOfIntsToBooleansReading.smithy4sJson       128  thrpt    5    124155.756 ±    1050.857  ops/s
[info] MapOfIntsToBooleansWriting.smithy4sJson       128  thrpt    5    683354.755 ±   22425.528  ops/s
[info] MissingRequiredFieldsReading.smithy4sJson     N/A  thrpt    5   5004746.466 ±  228617.676  ops/s
[info] NestedStructsReading.smithy4sJson             128  thrpt    5     95440.635 ±    1025.517  ops/s
[info] NestedStructsWriting.smithy4sJson             128  thrpt    5    374747.722 ±   41716.825  ops/s
[info] OpenRTBReading.smithy4sJson                   N/A  thrpt    5    188289.829 ±    3796.082  ops/s
[info] OpenRTBWriting.smithy4sJson                   N/A  thrpt    5    386514.174 ±    7588.826  ops/s
[info] PrimitivesReading.smithy4sJson                N/A  thrpt    5   1429732.700 ±   28112.858  ops/s
[info] PrimitivesWriting.smithy4sJson                N/A  thrpt    5   8308239.922 ±  408246.585  ops/s
[info] SetOfIntsReading.smithy4sJson                 128  thrpt    5    119789.079 ±    1937.745  ops/s
[info] SetOfIntsWriting.smithy4sJson                 128  thrpt    5    986635.158 ±    3518.802  ops/s
[info] StringOfAsciiCharsReading.smithy4sJson        128  thrpt    5  15049878.638 ±  738018.254  ops/s
[info] StringOfAsciiCharsWriting.smithy4sJson        128  thrpt    5   6291572.281 ±   24281.618  ops/s
[info] StringOfEscapedCharsReading.smithy4sJson      128  thrpt    5   3487470.924 ±  190335.583  ops/s
[info] StringOfEscapedCharsWriting.smithy4sJson      128  thrpt    5   4119490.415 ±   98874.969  ops/s
[info] StringOfNonAsciiCharsReading.smithy4sJson     128  thrpt    5   3563744.033 ±   25424.924  ops/s
[info] StringOfNonAsciiCharsWriting.smithy4sJson     128  thrpt    5   4476121.474 ±   94780.287  ops/s
[info] TwitterAPIReading.smithy4sJson                N/A  thrpt    5     34715.016 ±     833.851  ops/s
[info] TwitterAPIWriting.smithy4sJson                N/A  thrpt    5    103308.388 ±    4225.569  ops/s
[info] VectorOfBooleansReading.smithy4sJson          128  thrpt    5    303936.689 ±    1905.530  ops/s
[info] VectorOfBooleansWriting.smithy4sJson          128  thrpt    5   1660331.555 ±    5172.427  ops/s
```

**Comment by Baccata** [comment]
Cool there seem any noticeable impact of performance. 

> I'll add a test case to ensure it's not checked and will fix if required

This is the only thing that is required for this PR to be merged. 

@plokhotnyuk, please be aware of this PR. We had changed the internal representation of `Schema` to make it easier for people to understand how interpreters work, and make the project more maintainable generally. `SchemaVisitor` is conceptually similar to `Schematic` except that it retains the `Schema` construct for longer. This requires the caller to manually `apply` the recursion, but makes it easier to pass context from layer to layer, and could even allow for interpreters to delegate some logic to other interpreters. 

If you have some changes in flight that touch the json module, I'd appreciate if you rebased against this branch :)

**Comment by daddykotex** [comment]
> This is the only thing that is required for this PR to be merged.

I just added a test and it worked as expected

**Review by Baccata — APPROVED** [review]
Great work :)

**Pull request merged**
