### PR TITLE
Bump mdoc and use check-link-hygiene

### PR DESCRIPTION
**Pull request by daddykotex**

### CODE REVIEW

**Comment by kubukoz** [comment]
I've noticed that `--check` kills the entire sbt when it fails, so this probably does as well...

**Comment by daddykotex** [comment]
yeah, I've heard that in some places, although the logs show that mdoc did not produce any errors

Screen Shot 2022-09-26 at 12 10 56

**Comment by daddykotex** [comment]
well that's it, and it sucks, will fix upstream, what the hell

**Comment by kubukoz** [comment]
please fix `--check` too and I'll give you... a dollar, maybe two! :D

**Comment by daddykotex** [comment]
loll, look at that: https://github.com/scalameta/mdoc/pull/704/files#diff-2cc284217cfe2824b47da67d6861a834438a39647641d6c7493e1604c464dfb6L73

**Pull request closed without merging**
